[testing] activation test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -48,54 +48,54 @@ jobs:
             nondoc:
               - '!**/*.md'
 
-  ## stage 1: run unit tests and app tests as a prerequisite
-  ## these run on all pushes to all pull requests, all branches
-  ## note that secrets may not be accessible in this phase
-  quicktests:
-    runs-on: ubuntu-latest
-    needs: filter-changes
-    if: ${{ needs.filter-changes.outputs.nondocchanges == 'true' }}
-    # should not take more than 2-3 mins
-    timeout-minutes: 5
-    steps:
-      - name: Add OpenCL support
-        run: sudo apt-get update -q && sudo apt-get install -qy ocl-icd-opencl-dev libpocl2
-      - name: checkout
-        uses: actions/checkout@v4
-      - name: set up go
-        uses: actions/setup-go@v4
-        with:
-          check-latest: true
-          go-version: ${{ env.go-version }}
-      - name: fmt, tidy, generate
-        run: |
-          make install
-          make test-fmt
-          make test-tidy
-          make test-generate
+  # ## stage 1: run unit tests and app tests as a prerequisite
+  # ## these run on all pushes to all pull requests, all branches
+  # ## note that secrets may not be accessible in this phase
+  # quicktests:
+  #   runs-on: ubuntu-latest
+  #   needs: filter-changes
+  #   if: ${{ needs.filter-changes.outputs.nondocchanges == 'true' }}
+  #   # should not take more than 2-3 mins
+  #   timeout-minutes: 5
+  #   steps:
+  #     - name: Add OpenCL support
+  #       run: sudo apt-get update -q && sudo apt-get install -qy ocl-icd-opencl-dev libpocl2
+  #     - name: checkout
+  #       uses: actions/checkout@v4
+  #     - name: set up go
+  #       uses: actions/setup-go@v4
+  #       with:
+  #         check-latest: true
+  #         go-version: ${{ env.go-version }}
+  #     - name: fmt, tidy, generate
+  #       run: |
+  #         make install
+  #         make test-fmt
+  #         make test-tidy
+  #         make test-generate
 
-  lint:
-    runs-on: ubuntu-latest
-    needs: filter-changes
-    if: ${{ needs.filter-changes.outputs.nondocchanges == 'true' }}
-    # should not take more than 15-16 mins
-    timeout-minutes: 18
-    steps:
-      - name: Add OpenCL support
-        run: sudo apt-get update -q && sudo apt-get install -qy ocl-icd-opencl-dev libpocl2
-      - name: checkout
-        uses: actions/checkout@v4
-      - name: set up go
-        uses: actions/setup-go@v4
-        with:
-          check-latest: true
-          go-version: ${{ env.go-version }}
-      - name: setup env
-        run: make install
-      - name: staticcheck
-        run: make staticcheck
-      - name: lint
-        run: make lint-github-action
+  # lint:
+  #   runs-on: ubuntu-latest
+  #   needs: filter-changes
+  #   if: ${{ needs.filter-changes.outputs.nondocchanges == 'true' }}
+  #   # should not take more than 15-16 mins
+  #   timeout-minutes: 18
+  #   steps:
+  #     - name: Add OpenCL support
+  #       run: sudo apt-get update -q && sudo apt-get install -qy ocl-icd-opencl-dev libpocl2
+  #     - name: checkout
+  #       uses: actions/checkout@v4
+  #     - name: set up go
+  #       uses: actions/setup-go@v4
+  #       with:
+  #         check-latest: true
+  #         go-version: ${{ env.go-version }}
+  #     - name: setup env
+  #       run: make install
+  #     - name: staticcheck
+  #       run: make staticcheck
+  #     - name: lint
+  #       run: make lint-github-action
 
   build:
     runs-on: ${{ matrix.os }}
@@ -105,10 +105,10 @@ jobs:
       fail-fast: true
       matrix:
         os:
-          - ubuntu-latest
-          - [self-hosted, linux, arm64]
-          - macos-latest
-          - [self-hosted, macos, arm64]
+          # - ubuntu-latest
+          # - [self-hosted, linux, arm64]
+          # - macos-latest
+          # - [self-hosted, macos, arm64]
           - windows-latest
     steps:
       - name: Add OpenCL support - Ubuntu
@@ -206,30 +206,30 @@ jobs:
           report_paths: "**/unit-tests.xml"
           annotate_only: true
 
-  ci-status:
-    # run regardless of status of previous jobs but skip if the required secret is not accessible
-    if: always()
-    needs:
-      - filter-changes
-      - quicktests
-      - lint
-      - build
-      - unittests
-    runs-on: ubuntu-latest
-    env:
-      # short-circuit success if no non-doc files were modified
-      # this is the easiest way to access success/failure state of previous jobs in this workflow
-      status: ${{ (needs.filter-changes.outputs.nondocchanges == 'false' || (needs.quicktests.result == 'success' && needs.build.result == 'success' && needs.lint.result == 'success' && needs.unittests.result == 'success')) && 'success' || 'failure' }}
-    steps:
-      - uses: act10ns/slack@v2
-        name: Slack notification
-        # skip if the secret is not accessible
-        if: env.SLACK_WEBHOOK_URL
-        with:
-          status: ${{ env.status }}
-      - name: Mark the job as succeeded
-        if: env.status == 'success'
-        run: exit 0
-      - name: Mark the job as failed
-        if: env.status != 'success'
-        run: exit 1
+  # ci-status:
+  #   # run regardless of status of previous jobs but skip if the required secret is not accessible
+  #   if: always()
+  #   needs:
+  #     - filter-changes
+  #     - quicktests
+  #     - lint
+  #     - build
+  #     - unittests
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     # short-circuit success if no non-doc files were modified
+  #     # this is the easiest way to access success/failure state of previous jobs in this workflow
+  #     status: ${{ (needs.filter-changes.outputs.nondocchanges == 'false' || (needs.quicktests.result == 'success' && needs.build.result == 'success' && needs.lint.result == 'success' && needs.unittests.result == 'success')) && 'success' || 'failure' }}
+  #   steps:
+  #     - uses: act10ns/slack@v2
+  #       name: Slack notification
+  #       # skip if the secret is not accessible
+  #       if: env.SLACK_WEBHOOK_URL
+  #       with:
+  #         status: ${{ env.status }}
+  #     - name: Mark the job as succeeded
+  #       if: env.status == 'success'
+  #       run: exit 0
+  #     - name: Mark the job as failed
+  #       if: env.status != 'success'
+  #       run: exit 1
